### ISSUE TITLE
Error sending notification if Action exist

### ISSUE THREAD

**Issue by KJTamas** [notify-events/homebridge#3]
Hi,

If i create a notification without Action, works fine. I would like to try Actions (Documentation not clear for me🤷🏻‍♂️)

If i check Enable Actions, and fill the form as you descirbed in Example.json, i got an error message:
[NotifyEvents] Error: Send message fail with message "Cannot read properties of undefined (reading 'name')”

The config:
"platform": "NotifyEvents",
            "action": {
                "enabled": true,
                "listen": "0.0.0.0",
                "port": 53535,
                "host": "my ddns host name",
                "path": "/"
            },
            "channels": [
                {
                    "title": "My.Notify.Events",
                    "token": "XXXXXXXXXXXXXXX",
                    "messages": [
                        {
                            "name": "Notify test",
                            "title": "Sleep",
                            "text": "Go to sleep!",
                            "priority": "normal",
                            "level": "info",
                            "images": [],
                            "files": [],
                            "actions": [
                                {
                                    "name": "Sleep",
                                    "title": "Click Me"
                                }
                            ]
                        }
                    ]
                }
            ]

I tried to roll back to prev version.
Node.js:  v16.15.0
Config UI: 4.50.0
Notify.events: 1.3.1

Please help me, what can i do.

**Comment by matrozov** [comment]
Thank you for your message. By an absurd coincidence, the core library was published with incorrect code. We fixed this issue and updated the dependencies. In version 1.3.2 everything should be fine. Thank you.

**Comment by KJTamas** [comment]
Hi,

I tested, and works fine!

Thank you!
